name: Link checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v2

      - name: Link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --no-progress **/*.html **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create issue from file
        if: steps.lychee.outputs.exit_code != 0 # Only create an issue if there are errors
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
